version: '3'

services:
  postgres:
    image: circleci/postgres:12.2-ram
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
